from collections.abc import Mapping
from fractions import Fraction
from typing import Any

Exponent = int | Fraction
Dimensions = Mapping[str, Exponent]

CATALOG_SCHEMA: int
SI_BASES: tuple[str, ...]

class BridgmanError(Exception):
    """A refusal by the Rust core. `fields` is what the Rust variant names."""

    fields: Any

class _ErrorEnum(type):
    """A Rust error enum's class. Each of its variants is a subclass of it, set
    on it by name (`QuantityError.KindMismatch`); `variants` names them all."""

    variants: tuple[str, ...]
    def __getattr__(cls, variant: str) -> type[BridgmanError]: ...

class CatalogError(BridgmanError, metaclass=_ErrorEnum): ...
class QuantityError(BridgmanError, metaclass=_ErrorEnum): ...
class DerivationError(BridgmanError, metaclass=_ErrorEnum): ...
class DimensionError(BridgmanError, metaclass=_ErrorEnum): ...
class OperationParseError(BridgmanError, metaclass=_ErrorEnum): ...

def canonicalize_dims(value: Dimensions) -> dict[str, Exponent]: ...
def mul_dims(left: Dimensions, right: Dimensions) -> dict[str, Exponent]: ...
def div_dims(left: Dimensions, right: Dimensions) -> dict[str, Exponent]: ...
def pow_dims(value: Dimensions, power: Exponent | None) -> dict[str, Exponent]: ...
def common_dims(left: Dimensions, right: Dimensions) -> dict[str, Exponent]: ...
def transcendental_dims(value: Dimensions) -> dict[str, Exponent]: ...
def dims_equal(left: Dimensions, right: Dimensions) -> bool: ...
def dims_signature(value: Dimensions) -> str: ...
def parse_dims_signature(signature: str) -> dict[str, Exponent]: ...
def count_pi_groups(quantities: Mapping[str, Dimensions]) -> int: ...
def pi_groups(quantities: Mapping[str, Dimensions]) -> tuple[dict[str, int], ...]: ...

class NativeKindRegistry:
    def __init__(self, catalog: str) -> None: ...
    @staticmethod
    def bundled() -> NativeKindRegistry: ...
    def kinds(self) -> list[str]: ...
    def kind_dimensions(self, name: str) -> dict[str, Exponent]: ...
    def result_kind(self, left: str | None, op: str, right: str | None) -> str | None: ...
    def power_kind(self, base: str | None, exponent: Exponent | None) -> str | None: ...
    def absolute_kind(self, kind: str | None) -> str | None: ...
    def same_kind(self, left: str | None, right: str | None) -> str | None: ...
    def row_provenance(self, left: str, op: str, right: str) -> str | None: ...
    def kinds_with_dimensions(self, value: Dimensions) -> list[str]: ...
