"""Private native dimension arithmetic surface."""

def clean(dimensions: dict[str, int], /) -> dict[str, int]: ...
def canonicalize_dims(dimensions: dict[str, int], /) -> dict[str, int]: ...
def mul_dims(
    left: dict[str, int], right: dict[str, int], /
) -> dict[str, int]: ...
def div_dims(
    left: dict[str, int], right: dict[str, int], /
) -> dict[str, int]: ...
def pow_dims(dimensions: dict[str, int], exponent: int, /) -> dict[str, int]: ...
def dims_equal(left: dict[str, int], right: dict[str, int], /) -> bool: ...
def is_dimensionless(dimensions: dict[str, int], /) -> bool: ...
def format_dims(dimensions: dict[str, int], /) -> str: ...
def dims_signature(dimensions: dict[str, int], /) -> str: ...
def parse_dims_signature(signature: str, /) -> dict[str, int]: ...
