from collections.abc import Mapping
from typing import Any

Dimensions = Mapping[str, int]

def canonicalize_dims(value: Dimensions) -> dict[str, int]: ...
def mul_dims(left: Dimensions, right: Dimensions) -> dict[str, int]: ...
def div_dims(left: Dimensions, right: Dimensions) -> dict[str, int]: ...
def pow_dims(value: Dimensions, power: int) -> dict[str, int]: ...
def dims_equal(left: Dimensions, right: Dimensions) -> bool: ...
def dims_signature(value: Dimensions) -> str: ...
def count_pi_groups(quantities: Mapping[str, Dimensions]) -> int: ...
def pi_groups(quantities: Mapping[str, Dimensions]) -> tuple[dict[str, int], ...]: ...

class NativeKindRegistry:
    def __init__(self, kinds: list[dict[str, Any]], rules: list[dict[str, Any]]) -> None: ...
    def kind_dimensions(self, name: str) -> dict[str, int]: ...
    def result_kind(self, left: str, op: str, right: str) -> str: ...
    def kinds_with_dimensions(self, value: Dimensions) -> list[str]: ...
